version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=asa
      - POSTGRES_PASSWORD=asa
      - POSTGRES_DB=wiimy_db_store
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://asa:asa@wiimistore001-postgres-1:5432/wiimy_db_store?schema=public
    volumes:
      - .:/app

# 🔹 Declaración del volumen aquí
volumes:
  postgres_data:
