# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=asa
      - POSTGRES_PASSWORD=asa
      - POSTGRES_DB=wiimy_db_store
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
  app:
    build:
      context: .  # Usa el directorio actual para encontrar el Dockerfile
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://asa:asa@postgres:5432/wiimy_db_store
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules  # Evita sobrescribir node_modules con los archivos locales
    command: ["npm", "run", "dev"]  # Usa npm run dev si es Next.js en desarrollo

volumes:
  postgres_data: