version: '3.8'

services:
  # Servicio para la aplicación (tu aplicación Next.js)
  app:
    build:
      context: .
      dockerfile: Dockerfile # Especifica el Dockerfile si lo necesitas
    ports:
      - "3000:3000"   # Expone el puerto 3000 para tu aplicación
    environment:
      - DATABASE_URL=postgresql://asa:asa@db:5432/wiimy_db_store # URL de conexión a la DB, "db" es el nombre del servicio de la base de datos
    depends_on:
      - db   # Indica que la app depende del contenedor de la base de datos

  # Servicio para la base de datos (PostgreSQL)
  db:
    image: postgres:13 # Usa la imagen oficial de PostgreSQL
    environment:
      POSTGRES_USER: asa
      POSTGRES_PASSWORD: asa
      POSTGRES_DB: wiimy_db_store  # Nombre de la base de datos que tu aplicación utilizará
    ports:
      - "5432:5432"   # Expone el puerto 5432 para conectar desde el host (opcional)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen para persistir los datos

# Volumen para la base de datos
volumes:
  postgres_data:
